# -*- coding: utf-8 -*-
"""sistem rekomendasi resep makan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFJ-dtbWDFW2DqHFsbK82TGZITuP3dt-

# Sistem Rekomendasi Resep Makanan

## Pengantar Dataset
Dataset yang digunakan pada project ini adalah Food.com Recipes and Interactions yang bersumber dari platform Food.com dan tersedia melalui Kaggle. Dataset ini berisi lebih dari 230.000 data resep makanan dengan berbagai atribut seperti nama resep, durasi memasak, tags, kandungan nutrisi, jumlah langkah memasak, deskripsi, daftar bahan, dan jumlah bahan. Dataset dipilih karena memiliki jumlah data yang besar, struktur data yang lengkap, serta relevan untuk pengembangan sistem rekomendasi resep makanan berdasarkan karakteristik bahan, waktu memasak, dan informasi nutrisi. Dari sisi etika penggunaan, dataset ini merupakan data publik dan tidak memuat identitas pribadi pengguna, namun tetap memiliki potensi bias karena berasal dari satu platform resep tertentu sehingga preferensi makanan yang ditampilkan dapat lebih merepresentasikan pengguna Food.com.

## Pre Processing Data

#### Import dan load data
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

df = pd.read_csv("RAW_recipes.csv")

"""#### Cek struktur dataset
Untuk melihat dimensi dataset (baris dan kolom) dengan atribut `.shape`, kemudian menampilkan 5 baris pertama untuk gambaran awal sebaran kolom
"""

print("Jumlah data:", df.shape)
print("\nData awal:")
df.head()

print(df.dtypes)

"""#### Cek missing value"""

df.isnull().sum()

"""Setelah dicek, terdapat missing value pada kolom name sebanyak 1 dan kolom description sebanyak 4979. Untuk menangani hal tersebut, perlu dilakukan penghapusan baris yang pada kolom name kosong dan imputasi konstan pada baris data yang kosong data pada kolom description

Penghapusan data pada baris yang terdapat data kosong di kolom name menggunakan `dropna(subset=["name"])`. Hal ini dilakukan karena judul masakan merupakan identitas utama sebuah resep. Sistem rekomendasi tidak bisa mengidentifikasi atau menyarankan sebuah menu makanan jika menu tidak memiliki nama, sehingga baris ini tidak bisa diimputasi dan harus dihapus.
"""

df.dropna(
    subset=["name"],
    inplace=True
)
df["name"].isnull().sum()

"""Untuk nilai kosong pada baris description dapat ditangani menggunakan imputasi konstan dengan mengisi nilai kosong menjadi "No description" menggunakan fungsi `.fillna()`. Data kosong pada kolom description masih dapat diimputasi karena dalam baris data tersebut masih ada kolom yang menyimpan informasi numerik yang valid. Data kosong di kolom description terdapat 4979 baris. Apabila dihapus, model akan kehilangan banyak data latih potensial."""

df["description"] = df[
    "description"
].fillna(
    "No description"
)

df.isnull().sum()

"""setelah diimputasi dan hapus data, saat dicek sudah tidak ada data kosong

Kemudian cek juga apa kah data ada yang terduplikasi atau tidak dengan fungsi `.duplicated`.
"""

df.duplicated().sum()

"""Dari hasil terlihat tidak ada data yang terduplikasi

---
##### unduh dataset yang sudah dibersihkan
"""

df.to_csv(
    "dataset_clean.csv",
    index=False
)

"""---

#### Parsing
Pada dataset, terdapat kolom yang menyimpan data dalam bentuk string. Jika diproses, python akan menganggapnya sebagai karakter biasa dan tidak dapat membaca angka angka gizi atau jumlah bahan di dalamnya.

Kolom yang merupakan terbaca string nakun harusnya dibaca sebagai array adalah kolom tags, nutrition, steps, dan ingredients. Bukti ini terlihat nyata dari hasil pengecekan tipe data menggunakan perintah df.dtypes yang menunjukkan bahwa keempat kolom tersebut berlabel object.
"""

print(type(df["nutrition"][0]))
print(type(df["ingredients"][0]))
print(type(df["tags"][0]))
print(type(df["steps"][0]))

"""Untuk menangani ini, dilakukan parsing dengan fungsi `ast.literal_eval`. String text nantinya akan diubah menjadi list (array)."""

import ast

df["nutrition"] = df[
    "nutrition"
].apply(
    ast.literal_eval
)

df["ingredients"] = df[
    "ingredients"
].apply(
    ast.literal_eval
)

df["tags"] = df[
    "tags"
].apply(
    ast.literal_eval
)

df["steps"] = df[
    "steps"
].apply(
    ast.literal_eval
)

print(type(df["nutrition"][0]))
print(type(df["ingredients"][0]))
print(type(df["tags"][0]))
print(type(df["steps"][0]))

"""---

#### EDA
Exploratory Data Analysis (EDA) dilakukan untuk mengenali karakterisitik sebaran data, mendeteksi outliers, serta melihat hubungan antar fitur sebelum data di training
"""

print("Jumlah data:", df.shape)

"""Sebelum melakukan visualisasi histogram, dilakukan analisis terhadap karakteristik statistik deskriptif awal. Langkah ini dilakukan untuk memetakan rentang nilai minimum, kuartil, hingga nilai maksimum dari fitur-fitur numerik yang tersedia pada dataset."""

df.describe()

"""Terdapat 3 fitur numerik, yaitu `minutes`, `n_ingredient`, dan `n_step`.

Fitur durasi memasak (minutes) memiliki nilai median (kuartil 50%), yaitu 40 menit, dengan kuartil 75% berada di angka 65 menit. Namun, pada nilai maksimum (max), ditemukan angka pencilan yang sangat tidak masuk akal sebesar 2.147484e+09 (lebih dari 2 miliar menit). Hal ini mengonfirmasi adanya human error atau data rusak (corrupted data) saat penginputan dari platform aslinya. Oleh karena itu, histogram khusus untuk minutes wajib dibuat untuk melihat secara visual seberapa parah tingkat kecondongan (skewness) distribusi data akibat hantaman pencilan raksasa tersebut.
"""

plt.figure(figsize=(8,5))

df["minutes"].hist(
    bins=50
)

plt.title("Distribusi Waktu Memasak")
plt.xlabel("Menit")
plt.ylabel("Jumlah Resep")

plt.show()

"""Grafik histogram untuk fitur minutes menunjukkan penumpukan data yang sangat ekstrem di pojok kiri dekat angka 0, sementara sumbu X melar sangat jauh hingga skala $2.0 \times 10^9$ (lebih dari 2 miliar menit). Fenomena visual yang sangat condong (highly skewed) ini menjadi bukti konkret adanya anomali data raksasa atau human error pada proses input data mentah dari platform aslinya.

---
"""

plt.figure(figsize=(8,5))

df["n_ingredients"].hist(
    bins=30
)

plt.title("Distribusi Jumlah Ingredients")
plt.xlabel("Jumlah Ingredients")
plt.ylabel("Jumlah Resep")

plt.show()

"""Grafik histogram untuk fitur n_ingredients membentuk kurva yang mendekati distribusi normal (bell-shaped curve) dengan kecondongan tipis ke arah kanan (right-skewed). Pola data terlihat sangat sehat dan masuk akal secara fisis, di mana puncak frekuensi tertinggi (modus) berada tepat pada angka 9 jenis bahan baku, dengan mayoritas sebaran data resep masakan berpusat di kisaran 5 hingga 12 bahan. Informasi sebaran yang konsisten ini membuktikan bahwa dataset memiliki karakteristik konten yang baik untuk sistem rekomendasi, sehingga model dapat dengan mudah memetakan profil makanan kategori "simpel" atau "kompleks" berdasarkan kuantitas bahan dasarnya.

---
"""

plt.figure(figsize=(8,5))

df["n_steps"].hist(
    bins=30
)

plt.title("Distribusi Jumlah Langkah")
plt.xlabel("Jumlah Steps")
plt.ylabel("Jumlah Resep")

plt.show()

"""Grafik histogram untuk fitur n_steps menunjukkan pola distribusi yang condong ke kanan (right-skewed distribution), di mana mayoritas data menumpuk padat pada area kiri grafik dan perlahan melandai seiring bertambahnya jumlah instruksi. Sebagian besar resep di dalam dataset terdeteksi membutuhkan tingkat kerumitan yang praktis, yakni berkisar antara 5 hingga 10 langkah pembuatan saja, sebelum akhirnya frekuensi resep menurun drastis secara eksponensial setelah melewati angka 20 langkah.

---

Selanjutnya, dilakukan proses validasi data konkret menggunakan perintah pengurutan (.sort_values()) untuk memverifikasi nilai-resep paling ekstrem di batas bawah dan batas atas dataset—yaitu memeriksa apakah resep dengan durasi 0 menit murni merupakan hidangan mentah (seperti jus atau salad) dan resep dengan 43 bahan memang logis di dunia nyata
"""

df[
    ["name","minutes"]
].sort_values(
    by="minutes"
).head(10)

df[
    ["name","n_ingredients"]
].sort_values(
    by="n_ingredients",
    ascending=False
).head(10)

"""---
Setelah memvalidasi data ekstrem melalui pengurutan tersebut, tahapan EDA dilanjutkan ke pembuatan Boxplot khusus untuk kolom waktu memasak (minutes).

Visualisasi menggunakan Boxplot ini difokuskan hanya pada fitur minutes karena kolom tersebut memiliki kecenderungan anomali pencilan (outlier) yang paling destruktif dibandingkan kolom jumlah langkah atau jumlah bahan yang secara logika memiliki batas maksimum normal. Grafik boxplot menampilkan sebaran ribuan titik pencilan yang melambung sangat jauh di atas nilai kuartil atas hingga menyentuh skala miliaran menit, yang secara fisis membuktikan adanya variasi data durasi memasak yang sangat jomplang akibat human error saat penginputan di platform aslinya.
"""

# boxplot
plt.figure(figsize=(8,5))

plt.boxplot(
    df["minutes"]
)

plt.title("Boxplot Waktu Memasak")

plt.show()

"""Grafik boxplot menunjukkan kotak data utama terkompresi hingga membentuk satu garis tipis di paling bawah akibat tertekan oleh keberadaan satu titik pencilan (extreme outlier) raksasa yang melambung ekstrem hingga skala 2 miliar menit

Kemudian selanjutnya pembuatan heatmap untuk mengukur kekuatan hubungan linear antar-variabel numerik. Grafik ini dibatasi hanya menggunakan 6 fitur inti (minutes, n_steps, n_ingredients, calories, fat, tag_count) untuk menghindari korelasi ganda dari unsur gizi sejenis seperti lemak jenuh, karbohidrat, atau gula, sekaligus menjaga keterbacaan grafik agar tidak terlalu padat sehingga pola hubungan antar-kelompok karakteristik utama resep dapat diinterpretasikan secara fokus dan optimal.
"""

numeric_cols = [
    "minutes",
    "n_steps",
    "n_ingredients",
    "calories",
    "fat",
    "tag_count"
]


df["calories"] = df["nutrition"].apply(lambda x: x[0])
df["fat"] = df["nutrition"].apply(lambda x: x[1])
df["tag_count"] = df["tags"].apply(len)

corr = df[numeric_cols].corr()

plt.figure(figsize=(10,7))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.title(
    "Heatmap Korelasi"
)

plt.show()

"""---
#### feature engineering
Tahap Feature Engineering dilakukan untuk memecah kolom nutrition menjadi 7 indikator zat gizi mandiri (kalori, lemak, gula, sodium, protein, lemak jenuh, dan karbohidrat) serta mengekstrak metrik kuantitas fisik hidangan seperti jumlah tag, jumlah bahan, jumlah langkah, hingga panjang karakter judul dan deskripsi resep, di mana langkah ini sangat urgen untuk mentransformasikan struktur gumpalan teks mentah menjadi sekumpulan matriks prediktor numerik ($X$) yang seragam agar model dapat menghitung bobot kemiripan profil nutrisi dan kompleksitas resep secara akurat
"""

# kalori
df["calories"] = df["nutrition"].apply(
    lambda x: x[0]
)

print(
    df[
        ["name", "calories"]
    ].head()
)

# nutrisi
df["fat"] = df["nutrition"].apply(
    lambda x: x[1]
)

print(
    df[
        ["name", "fat"]
    ].head()
)

# gula
df["sugar"] = df["nutrition"].apply(
    lambda x: x[2]
)

print(
    df[
        ["name", "sugar"]
    ].head()
)

# sodium
df["sodium"] = df["nutrition"].apply(
    lambda x: x[3]
)

print(
    df[
        ["name", "sodium"]
    ].head()
)

# protein
df["protein"] = df["nutrition"].apply(
    lambda x: x[4]
)

print(
    df[
        ["name", "protein"]
    ].head()
)

#saturated fat
df["saturated_fat"] = df["nutrition"].apply(
    lambda x: x[5]
)

print(
    df[
        ["name", "saturated_fat"]
    ].head()
)

# karbohidrat
df["carbohydrates"] = df["nutrition"].apply(
    lambda x: x[6]
)

print(
    df[
        ["name", "carbohydrates"]
    ].head()
)

# jumlah tag
df["tag_count"] = df["tags"].apply(
    len
)

print(
    df[
        ["name", "tag_count"]
    ].head()
)

# jumlah bahan
df["ingredient_count"] = df[
    "ingredients"
].apply(
    len
)

print(
    df[
        ["name", "ingredient_count"]
    ].head()
)

#jumlah langkah
df["step_count"] = df[
    "steps"
].apply(
    len
)

print(
    df[
        ["name", "step_count"]
    ].head()
)

# panjang nama resep
df["name_length"] = df[
    "name"
].astype(str).str.len()

print(
    df[
        ["name", "name_length"]
    ].head()
)

# panjang deskripsi
df["description_length"] = df[
    "description"
].astype(str).str.len()

print(
    df[
        ["name", "description_length"]
    ].head()
)

# cek hasil
print(
    df[
        [
            "name",
            "calories",
            "fat",
            "sugar",
            "protein",
            "tag_count",
            "ingredient_count",
            "step_count",
            "name_length"
        ]
    ].head()
)

"""---
#### encoding
encoding digunakan untuk mengubah data kategori pada main_tag menjadi indeks angka numerik shingga bisa diproses secara matematis oleh algoritma

Sebelumnya dilakukan ektrasi `tag` dengan fungsi `lamda` untuk membentuk kolom kategori baru bernama `main_tag`
"""

df["main_tag"] = df["tags"].apply(
    lambda x: x[0] if len(x) > 0 else "unknown"
)

print(
    df[
        ["name", "main_tag"]
    ].head()
)

"""Selanjutnya menerapkan labelencoder untuk mengubah string teks menjadi format angka indeks numerik agar bisa diproses secara matematis oleh algoritma"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["main_tag"] = le.fit_transform(
    df["main_tag"]
)

print(
    df[
        ["name", "main_tag"]
    ].head()
)

"""mapping data untuk menampilkan pemetaan label asli dengan hasil angka konversinya"""

mapping = dict(
    zip(
        le.classes_,
        le.transform(le.classes_)
    )
)

print(mapping)

"""#### Scaling
scalling dilakukan untuk menyetarakan skala rentang nilai dari seluruh kolom numerik agar algoritma tidak bias bada fitur yang memiliki angka besar saja.

tahap ini menggunakan standardscaler untuk meredam pencilan ekstrem durasi memasak tanpa merusak variasi pola data resep yang lain. kolom prdiktor dipisah, kemudian dihitung nilai rata-rata dan standar devisiasinya, kemudian seluruh angka dikonversi kedalam skala standar baru
"""

from sklearn.preprocessing import StandardScaler

numeric_cols = [
    "minutes",
    "n_steps",
    "n_ingredients",
    "calories",
    "fat",
    "sugar",
    "sodium",
    "protein",
    "saturated_fat",
    "carbohydrates",
    "tag_count",
    "ingredient_count",
    "step_count",
    "name_length",
    "description_length",
    "main_tag"
]

scaler = StandardScaler()

df_scaled = df.copy()

df_scaled[numeric_cols] = scaler.fit_transform(
    df_scaled[numeric_cols]
)

print(
    df_scaled[
        numeric_cols
    ].head()
)

"""#### train test split
data yang ada kemudian dipisah menjadi 80 untuk training dan 20 untuk testing. 80:20 dipilih karena menjadi standar umum dalam pemodelan. parameter random_state=42 disematkan untuk mengunci pengacakan data dan hasil pembagian tetap konsisten
"""

from sklearn.model_selection import train_test_split

X = df_scaled[
    [
        "minutes",
        "n_steps",
        "n_ingredients",
        "calories",
        "fat",
        "sugar",
        "sodium",
        "protein",
        "saturated_fat",
        "carbohydrates",
        "tag_count",
        "ingredient_count",
        "step_count",
        "name_length",
        "description_length"
    ]
]

y = df_scaled["main_tag"]

# split data 80:20
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Train:", X_train.shape)
print("Test :", X_test.shape)

"""#### save csv"""

df_scaled.to_csv(
    "food_recommendation_scaaling.csv",
    index=False
)

"""---
---
---

## Modeling

### Content-Based Filtering (Cosine Similarity)
"""

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

df_scaled = pd.read_csv("food_recommendation_scaaling.csv")

features = [
    "minutes",
    "calories",
    "fat",
    "ingredient_count",
    "tag_count",
    "main_tag"
]

X = df_scaled[features]

cosine_sim = cosine_similarity(X)

print("Matrix similarity berhasil dibuat")

def recommend_cosine(recipe_name, n=5):

    idx = df[
        df["name"].str.lower() ==
        recipe_name.lower()
    ].index

    if len(idx) == 0:
        return "Recipe not found"

    idx = idx[0]

    scores = list(
        enumerate(cosine_sim[idx])
    )

    scores = sorted(
        scores,
        key=lambda x: x[1],
        reverse=True
    )

    scores = scores[1:n+1]

    recipe_idx = [
        i[0] for i in scores
    ]

    return df[
        [
            "name",
            "minutes",
            "ingredient_count",
            "calories"
        ]
    ].iloc[recipe_idx]

df["name"].head(10)

"""### KNN"""